version: '3.9'
services:
  apache:
    image: httpd:latest
    container_name: app-apache-dio
    environment:
      MYSQL_ROOT_PASSWORD: "eve" 
    ports:
      - '80:80'
    volumes:
      - ./webproject:/usr/local/apache2/htdocs
